language: node_js
node_js:
  - '6'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm install
  - npm prune
  - npm run test-all
cache:
  directories:
    - node_modules
after_success:
  - npm run coverage
before_deploy:
  - npm run docs
deploy:
  -
    provider: pages
    local_dir: docs/
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      tags: true
